# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='upload_resume',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
