# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_applicationform_upload_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('PUBLISHED', 'Published')], default='PENDING', max_length=9),
        ),
    ]
